# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-03-23 17:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='comment',
            field=models.TextField(default=datetime.datetime(2016, 3, 23, 17, 48, 22, 140802, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
