# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-02-03 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Original',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple_text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='translation',
            name='hard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.Original'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='simple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.Simple'),
        ),
    ]
