# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-03-24 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_history_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Simplify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('output', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.Simplify'),
        ),
    ]
