# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-03-25 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0003_auto_20160324_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
    ]
