# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-03-25 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0004_remove_comment_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('hard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.Original')),
                ('simple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.Simple')),
            ],
        ),
        migrations.RemoveField(
            model_name='history',
            name='hard',
        ),
        migrations.RemoveField(
            model_name='history',
            name='simple',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
